name: ðŸš€ Build and deploy Portfolio
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: ðŸ—ï¸ Build Nextjs Application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ðŸ“¦ Install dependencies
        run: npm install

      - name: ðŸ”¨ Build application
        run: npm run build

      - name: ðŸ³ Build docker image
        run: docker build -t portfolio-isaac .

      - name: ðŸ”§ Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ” Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase Repo Slug
        run: |
          echo "REPO_SLUG=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker tag portfolio ghcr.io/${{ env.REPO_SLUG }}:latest
          docker push ghcr.io/${{ env.REPO_SLUG }}:latest
